name: dispensary
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3  
  provider: 6.1.1
  sqflite: 2.3.0
  path_provider: 2.1.1
  flutter_dotenv: 5.1.0
  autocomplete_textfield: ^2.0.1
  timeago: ^3.6.0
  intl: ^0.18.0
  pdf: ^3.10.7
  file_picker: ^6.1.1
  share_plus: 7.0.2
  permission_handler: ^11.2.0
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.2.1
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  http: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  faker: ^2.1.0
flutter:
  uses-material-design: true
  assets:
   - .env
   - assets/images/logo.png
