import 'dart:math';

import 'package:dispensary/models/medicine_model.dart';
import 'package:dispensary/models/prescription_line_model.dart';
import 'package:dispensary/models/prescription_model.dart';

class FakePrescriptionGenerator {
  static Prescription generateFakePrescription(int patientId) {
    // Generate random values for prescription details
    String details = 'Prescription details for patient $patientId';
    String diagnosis = 'Diagnosis for patient $patientId';
    String problem = 'Problem for patient $patientId';
    DateTime createdDate = DateTime.now();
    DateTime updatedDate = DateTime.now();
    double totalAmount = Random().nextDouble() * 100.0;
    double paidAmount = Random().nextDouble() * totalAmount;

    // Generate a random number of prescription lines
    int numberOfLines = Random().nextInt(5) + 1; // 1 to 5 lines

    // Generate prescription lines
    List<PrescriptionLine> prescriptionLines =
        List.generate(numberOfLines, (index) {
      return PrescriptionLine(
        sysPrescriptionLineId:
            index + 1, // Assuming sysPrescriptionLineId is auto-incremented
        medicine: Medicine(
          sysMedicineId: numberOfLines,
          name: 'Medicine $numberOfLines',
          description: 'Description for medicine $numberOfLines',
          createdDate: DateTime.now(),
          updatedDate: DateTime.now(),
        ),
        doses: 'Dose $index',
        duration: 'Duration $index',
        notes: 'Notes $index',
        strength: 'Strength $index',
      );
    });

    // Create and return the fake prescription
    return Prescription(
      sysPrescriptionId:
          0, // sysPrescriptionId will be auto-generated by the database
      prescriptionLines: prescriptionLines,
      patientId: patientId,
      details: details,
      diagnosis: diagnosis,
      problem: problem,
      createdDate: createdDate,
      updatedDate: updatedDate,
      totalAmount: totalAmount,
      paidAmount: paidAmount,
    );
  }
}
